In [6]:
import h5py
h5py.run_tests()

0

In [2]:
#
# This example writes data to the existing empty dataset created by h5_crtdat.py and then reads it back.
#
import h5py
import numpy as np
#
# Open an existing file using default properties.
#
file = h5py.File('dset.h5','r+')
#
# Open "dset" dataset under the root group.
#
dataset = file['/dset']
#
# Initialize data object with 0.
#
data = np.zeros((4,6))
#
# Assign new values
#
for i in range(4):
    for j in range(6):
        data[i][j]= i*6+j+1	 
#
# Write data
#
print("Writing data...")
dataset[...] = data
#
# Read data back and print it.
#
print("Reading data back...")
data_read = dataset[...]
print("Printing data...")
print(data_read)
#
# Close the file before exiting
#
file.close()


Writing data...
Reading data back...
Printing data...
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [4]:
#
# This examaple creates and writes two attributes on the "dset" dataset created by h5_crtdat.py.
#
import h5py
import numpy as np
#
# Open an existing file using defaut properties.
#
file = h5py.File('dset.h5','r+')
#
# Open "dset" dataset.
#
dataset = file['/dset']
#
# Create string attribute.
#
attr_string = "Meter per second"
dataset.attrs["Units"] = attr_string
#
# Create integer array attribute.
#
attr_data = np.zeros((2))
attr_data[0] = 100
attr_data[1] = 200
#
#
dataset.attrs.create("Speed", attr_data, (2,), h5py.h5t.STD_I32BE)
#
# Close the file before exiting
#
file.close()


In [5]:
#
# This example creates an HDF5 file group.h5 and a group MyGroup in it 
# using H5Py interfaces to the HDF5 library. 
#
import sys
import h5py

# Uncomment the next line if you want to save the output from this script to a file named "out".
#sys.stdout = open('out', 'w')
#
# Use 'w' to remove existing file and create a new one; use 'w-' if
# create operation should fail when the file already exists.
#
print("Creating an HDF5 file with the name group.h5...")
file = h5py.File('group.h5','w')
#
# Show the Root group which is created when the file is created.
#
print("When an HDF5 file is created, it has a Root group with the name '",file.name,"'.")
#
# Create a group with the name "MyGroup"
#
print("Creating a group MyGroup in the file...")
group = file.create_group("MyGroup")
# 
# Print the content of the Root group
#
print("An HDF5 group is a container for other objects; a group is similar to Python dictionary with the keys being the links to the group members.")
print("Show the members of the Root group using dictionary key method:", list(file.keys()))
#
# Another way to show the content of the Root group.
print("Show the members of the Root group using the list function:", list(file))
#
# Close the file before exiting; H5Py will close the group.
#
file.close()


Creating an HDF5 file with the name group.h5...
When an HDF5 file is created, it has a Root group with the name ' / '.
Creating a group MyGroup in the file...
An HDF5 group is a container for other objects; a group is similar to Python dictionary with the keys being the links to the group members.
Show the members of the Root group using dictionary key method: ['MyGroup']
Show the members of the Root group using the list function: ['MyGroup']
